version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...

      - git fetch --tags

      - AccountID=$(aws sts get-caller-identity --query "Account" --output text)

      - ECR_NAME=skills-repo

      - ECR_URI=$AccountID.dkr.ecr.ap-northeast-2.amazonaws.com/$ECR_NAME

      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin $AccountID.dkr.ecr.ap-northeast-2.amazonaws.com

      - IMAGE_TAG=$(git describe --tags --abbrev=0)

  build:
    commands:
      - docker build -t $ECR_URI:$IMAGE_TAG .

  post_build:
    commands:
      - docker push $ECR_URI:$IMAGE_TAG
