version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - AccountID=$(aws sts get-caller-identity --query "Account" --output text)
      - ECR_NAME=skills-repo
      - ECR_URI=$AccountID.dkr.ecr.ap-northeast-2.amazonaws.com/$ECR_NAME
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin $AccountID.dkr.ecr.ap-northeast-2.amazonaws.com

      # 자동 SemVer 태그 생성
      - LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
      - NEXT_TAG=$(echo $LATEST_TAG | awk -F. '{print $1"."$2"."$3+1}')
      - IMAGE_TAG=$NEXT_TAG
      - git tag $IMAGE_TAG
      - git push origin $IMAGE_TAG

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ECR_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $ECR_URI:$IMAGE_TAG
