apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blue-green-app
  namespace: app
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector: 
    matchLabels:
      app: rollout-bluegreen
  template:
    metadata:
      labels:
        app: rollout-bluegreen
    spec:
      containers:
      - name: rollouts-demo
        image: 959546961918.dkr.ecr.ap-northeast-2.amazonaws.com/skills-repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    blueGreen: 
      activeService: rollout-bluegreen-active
      previewService: rollout-bluegreen-preview
      autoPromotionEnabled: true
---
kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-active
  namespace: app
spec:
  selector:
    app: rollout-bluegreen
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-preview
  namespace: app
spec:
  selector:
    app: rollout-bluegreen
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: app
  name: blue-green-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: rollouts-test
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/tags: Name=skills-bule-green-alb
    alb.ingress.kubernetes.io/healthcheck-path: "/healthcheck"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - backend:
              service:
                name: rollout-bluegreen-preview
                port:
                  number: 80
            path: /
            pathType: Prefix
          - backend:
              service:
                name: rollout-bluegreen-preview
                port:
                  number: 80
            path: /healthcheck
            pathType: Prefix
