apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-app
  namespace: app
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-canary
  template:
    metadata:
      labels:
        app: rollout-canary
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: rollouts-demo
          image: 362708816803.dkr.ecr.ap-northeast-2.amazonaws.com/skills-repo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 820m
              memory: 3000Mi
            requests:
              cpu: 820m
              memory: 3000Mi
  strategy:
    canary:
      canaryService: rollout-canary-svc
      stableService: rollout-canary-svc-stable
      maxSurge: "20%"
      maxUnavailable: 1
      scaleDownDelaySeconds: 30
      steps:
        - setWeight: 10
        - setCanaryScale:
            weight: 10
        - pause:
            duration: 5m
        - pause: {}
        - setCanaryScale:
            matchTrafficWeight: true
      trafficRouting:
        alb:
          ingress: canary-ingress
          servicePort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: canary-hpa
  namespace: app
spec:
  maxReplicas: 6
  minReplicas: 3
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: canary-app
  targetCPUUtilizationPercentage: 60
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-canary-svc
  namespace: app
spec:
  selector:
    app: rollout-canary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-canary-svc-stable
  namespace: app
spec:
  selector:
    app: rollout-canary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: app
  name: canary-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: rollouts-test
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/tags: Name=skills-canary-alb
    alb.ingress.kubernetes.io/healthcheck-path: "/healthcheck"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - backend:
              service:
                name: rollout-canary-svc-stable
                port:
                  number: 80
            path: /
            pathType: Prefix
